# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-09-28T00:14:32+00:00

from __future__ import annotations

from fastapi import APIRouter

import sys
from typing import List, Optional, Union

sys.path.append("..")
from dependencies import *

router = APIRouter(tags=['Delete active session'])


@router.delete(
    '/api/v1/user/sessions/{session_id}',
    response_model=None,
    responses={
        '401': {'model': HTTPExceptionResponse},
        '404': {'model': HTTPExceptionResponse},
        '422': {'model': HTTPValidationError},
    },
    tags=['Delete active session'],
)
def end_user_session_api_v1_user_sessions__session_id__delete(
    session_id: UUID,
) -> Optional[Union[HTTPExceptionResponse, HTTPValidationError]]:
    """
    Delete session
    """
    pass
