# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-09-28T00:14:32+00:00

from __future__ import annotations

from fastapi import APIRouter

import sys
from typing import List, Optional, Union

sys.path.append("..")
from dependencies import *

router = APIRouter(tags=['History of user activity'])


@router.get(
    '/api/v1/user/sessions',
    response_model=List[SessionResponse],
    responses={
        '401': {'model': HTTPExceptionResponse},
        '422': {'model': HTTPValidationError},
    },
    tags=['History of user activity'],
)
def list_user_sessions_api_v1_user_sessions_get(
    active: Optional[bool] = None,
    page_size: Optional[conint(ge=1)] = 20,
    page_number: Optional[conint(ge=1)] = 1,
) -> Union[List[SessionResponse], HTTPExceptionResponse, HTTPValidationError]:
    """
    History of user activities
    """
    pass
