# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-09-28T00:14:32+00:00

from __future__ import annotations

from fastapi import APIRouter


import sys
sys.path.append("..")
from dependencies import *

router = APIRouter(tags=['Register'])


@router.post(
    '/api/v1/register',
    response_model=UserResponse,
    responses={
        '400': {'model': HTTPExceptionResponse},
        '422': {'model': HTTPValidationError},
    },
    tags=['Register'],
)
def register_api_v1_register_post(
    body: UserCreate,
) -> Union[UserResponse, HTTPExceptionResponse, HTTPValidationError]:
    """
    Registration
    """
    pass
