# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-09-28T00:14:32+00:00

from __future__ import annotations

from fastapi import APIRouter

import sys
sys.path.append("..")
from dependencies import *

router = APIRouter(tags=['User profile'])


@router.get(
    '/api/v1/user',
    response_model=UserResponse,
    responses={
        '401': {'model': HTTPExceptionResponse},
        '404': {'model': HTTPExceptionResponse},
    },
    tags=['User profile'],
)
def get_current_user_api_v1_user_get() -> Union[UserResponse, HTTPExceptionResponse]:
    """
    Get user profile
    """
    pass


@router.patch(
    '/api/v1/user',
    response_model=UserResponse,
    responses={
        '401': {'model': HTTPExceptionResponse},
        '404': {'model': HTTPExceptionResponse},
        '422': {'model': HTTPValidationError},
    },
    tags=['User profile'],
)
def patch_current_user_api_v1_user_patch(
    body: UserPatch,
) -> Union[UserResponse, HTTPExceptionResponse, HTTPValidationError]:
    """
    Change user profile
    """
    pass
