# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-09-28T00:14:32+00:00

from __future__ import annotations

from typing import List, Optional, Union
from uuid import UUID

from pydantic import conint

from models import (
    AllowRole,
    BodyCreateUserRoleApiV1UsersUserIdRolesPost,
    BodyDeleteUserRoleApiV1UsersUserIdRolesDelete,
    BodyRefreshTokensApiV1RefreshTokensPost,
    Credentials,
    HTTPExceptionResponse,
    HTTPValidationError,
    RoleBase,
    RoleResponse,
    SessionResponse,
    TokenPair,
    UserCreate,
    UserPatch,
    UserResponse,
)
