# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2024-09-28T00:14:32+00:00

from __future__ import annotations

from fastapi import FastAPI

from routers import (
    authorization,
    delete_active_session,
    history_of_user_activity,
    manage_access,
    manage_roles,
    register,
    user_profile,
)

app = FastAPI(
    title='auth',
    version='0.1.0',
    docs_url="/api/openapi",
    openapi_url="/api/openapi.json",
)

app.include_router(authorization.router)
app.include_router(delete_active_session.router)
app.include_router(history_of_user_activity.router)
app.include_router(manage_access.router)
app.include_router(manage_roles.router)
app.include_router(register.router)
app.include_router(user_profile.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
